'use client';

import { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, X, Loader2, FileArchive, CheckCircle } from 'lucide-react';
import JSZip from 'jszip';

type Stack = 'sentinel' | 'splunk' | 'crowdstrike' | 'mde';

interface PackageBundlerProps {
  pkg: {
    id: string;
    name: string;
    summary: string;
    mitre: string[];
    includes: string[];
    repo_path: string;
  };
  onClose: () => void;
}

const stacks: { id: Stack; label: string; desc: string; color: string; bg: string; border: string }[] = [
  { id: 'sentinel', label: 'Microsoft Sentinel', desc: 'KQL detection rules + Azure Logic Apps', color: 'text-cyan-400', bg: 'bg-cyan-400/10', border: 'border-cyan-400/30' },
  { id: 'splunk', label: 'Splunk', desc: 'SPL correlation rules + SOAR playbooks', color: 'text-green-400', bg: 'bg-green-400/10', border: 'border-green-400/30' },
  { id: 'crowdstrike', label: 'CrowdStrike', desc: 'IOA indicators + Falcon containment', color: 'text-purple-400', bg: 'bg-purple-400/10', border: 'border-purple-400/30' },
  { id: 'mde', label: 'Microsoft Defender (MDE)', desc: 'Advanced hunting queries + response actions', color: 'text-amber-400', bg: 'bg-amber-400/10', border: 'border-amber-400/30' },
];

/* Vendor-specific content generators */
function generateDetectionRule(pkg: PackageBundlerProps['pkg'], stack: Stack): string {
  const mitreStr = pkg.mitre.join(', ');
  switch (stack) {
    case 'sentinel':
      return `// SOaC Detection Rule for Microsoft Sentinel
// Package: ${pkg.name} (${pkg.id})
// MITRE ATT&CK: ${mitreStr}
// Auto-generated by SOaC Enterprise Package Bundler

let timeWindow = 5m;
let threshold = 2;
SigninLogs
| where TimeGenerated > ago(timeWindow)
| where ResultType == "0"
| summarize
    UniqueIPs = dcount(IPAddress),
    UniqueLocations = dcount(Location),
    IPList = make_set(IPAddress),
    LocationList = make_set(Location)
    by UserPrincipalName, AppDisplayName
| where UniqueIPs > threshold and UniqueLocations > 1
| extend
    RiskScore = case(
        UniqueLocations >= 3, "CRITICAL",
        UniqueIPs >= 4, "HIGH",
        "MEDIUM"
    ),
    MITREAttack = "${mitreStr}"
| project TimeGenerated=now(), UserPrincipalName, RiskScore, UniqueIPs, UniqueLocations, IPList, LocationList, MITREAttack
`;
    case 'splunk':
      return `| ============================================================
| SOaC Detection Rule for Splunk
| Package: ${pkg.name} (${pkg.id})
| MITRE ATT&CK: ${mitreStr}
| Auto-generated by SOaC Enterprise Package Bundler
| ============================================================

index=main sourcetype=auth_logs
| stats
    dc(src_ip) as unique_ips,
    dc(src_geo) as unique_geos,
    values(src_ip) as ip_list,
    values(src_geo) as geo_list,
    count as event_count,
    earliest(_time) as first_seen,
    latest(_time) as last_seen
    by user, session_id
| eval time_window_seconds = last_seen - first_seen
| where unique_ips > 2 AND unique_geos > 1 AND time_window_seconds < 300
| eval risk_score = case(
    unique_geos >= 3, "CRITICAL",
    unique_ips >= 4, "HIGH",
    1=1, "MEDIUM"
  )
| eval mitre_attack = "${mitreStr}"
| table user, risk_score, unique_ips, unique_geos, ip_list, geo_list, event_count, time_window_seconds, mitre_attack
| sort - risk_score
`;
    case 'crowdstrike':
      return `# SOaC Detection Rule for CrowdStrike Falcon
# Package: ${pkg.name} (${pkg.id})
# MITRE ATT&CK: ${mitreStr}
# Auto-generated by SOaC Enterprise Package Bundler
#
# Custom IOA Rule Configuration
# Import via Falcon Console > Custom IOA Rule Groups

rule_name: "SOaC - ${pkg.name}"
rule_type: "custom_ioa"
enabled: true
severity: "critical"
mitre_attack:
${pkg.mitre.map(m => `  - ${m}`).join('\n')}

# Detection Logic
platform: ["Windows", "Mac", "Linux"]
event_type: "ProcessRollup2"
field_values:
  - field: "CommandLine"
    operator: "CONTAINS"
    values:
      - "suspicious_pattern_1"
      - "suspicious_pattern_2"
  - field: "ParentImageFileName"
    operator: "NOT_CONTAINS"
    values:
      - "legitimate_parent.exe"

response_actions:
  - action: "detect"
    severity: "critical"
  - action: "prevent"
    severity: "critical"
`;
    case 'mde':
      return `// SOaC Detection Rule for Microsoft Defender for Endpoint
// Package: ${pkg.name} (${pkg.id})
// MITRE ATT&CK: ${mitreStr}
// Auto-generated by SOaC Enterprise Package Bundler
//
// Advanced Hunting Query
// Paste into Microsoft 365 Defender > Hunting > Advanced Hunting

DeviceLogonEvents
| where Timestamp > ago(5m)
| where LogonType == "Interactive" or LogonType == "RemoteInteractive"
| summarize
    UniqueIPs = dcount(RemoteIP),
    UniqueDevices = dcount(DeviceName),
    IPList = make_set(RemoteIP),
    DeviceList = make_set(DeviceName)
    by AccountName, AccountDomain
| where UniqueIPs > 2
| extend
    RiskScore = iff(UniqueIPs >= 4, "CRITICAL", iff(UniqueIPs >= 3, "HIGH", "MEDIUM")),
    MITREAttack = "${mitreStr}"
| project Timestamp=now(), AccountName, AccountDomain, RiskScore, UniqueIPs, UniqueDevices, IPList, DeviceList, MITREAttack
| sort by RiskScore desc
`;
  }
}

function generatePlaybook(pkg: PackageBundlerProps['pkg'], stack: Stack): string {
  const mitreStr = pkg.mitre.join(', ');
  const targets: Record<Stack, string> = {
    sentinel: 'Azure Logic App / Microsoft Sentinel Automation Rule',
    splunk: 'Splunk SOAR (Phantom) Playbook',
    crowdstrike: 'CrowdStrike Falcon RTR Script',
    mde: 'Microsoft Defender Live Response Script',
  };

  return `# CLAW Playbook - ${targets[stack]}
# Package: ${pkg.name} (${pkg.id})
# MITRE ATT&CK: ${mitreStr}
# Auto-generated by SOaC Enterprise Package Bundler

apiVersion: claw.soac.io/v1
kind: Playbook
metadata:
  name: ${pkg.id}-response
  version: "1.0.0"
  author: soac-bundler
  severity: CRITICAL
  mitre_attack:
${pkg.mitre.map(m => `    - ${m}`).join('\n')}
  tags:
    - auto-generated
    - ${stack}
    - ${pkg.id}

spec:
  description: >-
    Automated response playbook for ${pkg.name}.
    Target platform: ${targets[stack]}.

  trigger:
    source: BODY
    conditions:
      - field: package_id
        operator: eq
        value: "${pkg.id}"
      - field: risk_score
        operator: eq
        value: "CRITICAL"
    cooldown: 5m

  steps:
    - id: enrich
      name: Enrich Threat Context
      action: api_call
      target: ${stack}
      params:
        method: GET
      timeout: 10s
      on_failure: abort

    - id: contain
      name: Containment Action
      action: api_call
      target: ${stack}
      params:
        method: POST
      timeout: 15s
      on_failure: escalate

    - id: notify
      name: Alert SOC Team
      action: notify
      target: slack
      params:
        channel: "#soc-critical"
      on_failure: continue

  governance:
    requires_approval: false
    max_blast_radius: single_user
    audit_level: verbose
    brain_oversight: true
`;
}

function generateReadme(pkg: PackageBundlerProps['pkg'], stack: Stack): string {
  const stackLabel = stacks.find(s => s.id === stack)?.label ?? stack;
  return `# ${pkg.name} — ${stackLabel} Export

**Package ID:** ${pkg.id}  
**Stack:** ${stackLabel}  
**MITRE ATT&CK:** ${pkg.mitre.join(', ')}  
**Generated by:** SOaC Enterprise Package Bundler  

## Overview

${pkg.summary}

## Contents

| File | Description |
|------|-------------|
| \`detection_rule.*\` | Vendor-specific detection rule for ${stackLabel} |
| \`response_playbook.yaml\` | CLAW playbook adapted for ${stackLabel} |
| \`README.md\` | This file |

## Deployment

1. Review the detection rule and adjust thresholds for your environment.
2. Import the detection rule into your ${stackLabel} instance.
3. Review and customize the CLAW playbook parameters.
4. Test in a lab environment before production deployment.
5. Enable monitoring and validate detections.

## Includes

${pkg.includes.map(inc => `- ${inc}`).join('\n')}

## Source

This package was generated from the SOaC Enterprise repository.  
For the latest version, visit: https://github.com/ge0mant1s/SOaC-Enterprise

---
*SOaC — Security Operations as Code. Built by operators, for operators.*
`;
}

export default function PackageBundler({ pkg, onClose }: PackageBundlerProps) {
  const [selectedStack, setSelectedStack] = useState<Stack | null>(null);
  const [generating, setGenerating] = useState(false);
  const [done, setDone] = useState(false);

  const handleGenerate = useCallback(async () => {
    if (!selectedStack) return;
    setGenerating(true);

    // Small delay for UX
    await new Promise(r => setTimeout(r, 600));

    const zip = new JSZip();
    const folder = zip.folder(`${pkg.id}_${selectedStack}`);
    if (!folder) return;

    // Detection rule
    const ext: Record<Stack, string> = { sentinel: 'kql', splunk: 'spl', crowdstrike: 'yaml', mde: 'kql' };
    folder.file(`detection_rule.${ext[selectedStack]}`, generateDetectionRule(pkg, selectedStack));

    // Playbook
    folder.file('response_playbook.yaml', generatePlaybook(pkg, selectedStack));

    // README
    folder.file('README.md', generateReadme(pkg, selectedStack));

    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${pkg.id}_${selectedStack}_export.zip`;
    a.click();
    URL.revokeObjectURL(url);

    setGenerating(false);
    setDone(true);
    setTimeout(() => { setDone(false); onClose(); }, 1500);
  }, [selectedStack, pkg, onClose]);

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center p-4"
        onClick={onClose}
      >
        {/* Backdrop */}
        <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />

        {/* Modal */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          onClick={(e) => e.stopPropagation()}
          className="relative w-full max-w-lg glass-card rounded-lg border border-terminal/20 shadow-2xl overflow-hidden"
        >
          {/* Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-terminal/10">
            <div>
              <h3 className="font-mono text-sm font-semibold text-foreground flex items-center gap-2">
                <FileArchive className="w-4 h-4 text-terminal" />
                Custom Export
              </h3>
              <p className="font-mono text-[10px] text-muted-foreground mt-0.5">{pkg.name} ({pkg.id})</p>
            </div>
            <button onClick={onClose} className="p-1.5 rounded hover:bg-muted/50 text-muted-foreground hover:text-foreground transition-all">
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Body */}
          <div className="px-6 py-5">
            <p className="font-mono text-xs text-muted-foreground mb-4">Select your stack to generate a vendor-specific .zip bundle:</p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {stacks.map((s) => (
                <button
                  key={s.id}
                  onClick={() => setSelectedStack(s.id)}
                  className={`text-left p-3 rounded-md border-2 transition-all font-mono ${
                    selectedStack === s.id
                      ? `${s.border} ${s.bg}`
                      : 'border-border/30 hover:border-border/60 bg-muted/10'
                  }`}
                >
                  <span className={`text-xs font-semibold ${selectedStack === s.id ? s.color : 'text-foreground'}`}>
                    {s.label}
                  </span>
                  <span className="block text-[10px] text-muted-foreground mt-0.5">{s.desc}</span>
                </button>
              ))}
            </div>

            {selectedStack && (
              <motion.div initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} className="mt-4 p-3 rounded-md bg-muted/20 border border-border/30">
                <p className="font-mono text-[10px] text-muted-foreground">Bundle will include:</p>
                <ul className="mt-1 space-y-0.5">
                  <li className="font-mono text-[10px] text-foreground">\u2713 detection_rule.{selectedStack === 'crowdstrike' ? 'yaml' : selectedStack === 'splunk' ? 'spl' : 'kql'}</li>
                  <li className="font-mono text-[10px] text-foreground">\u2713 response_playbook.yaml</li>
                  <li className="font-mono text-[10px] text-foreground">\u2713 README.md</li>
                </ul>
              </motion.div>
            )}
          </div>

          {/* Footer */}
          <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-terminal/10">
            <button onClick={onClose} className="px-4 py-2 rounded-md font-mono text-xs bg-muted/50 text-muted-foreground border border-border hover:border-terminal/30 transition-all">
              Cancel
            </button>
            <button
              onClick={handleGenerate}
              disabled={!selectedStack || generating}
              className="flex items-center gap-2 px-5 py-2 rounded-md font-mono text-xs font-semibold bg-terminal/20 text-terminal border border-terminal/30 hover:bg-terminal/30 disabled:opacity-30 transition-all"
            >
              {done ? (
                <><CheckCircle className="w-3.5 h-3.5" /> Downloaded!</>
              ) : generating ? (
                <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating...</>
              ) : (
                <><Download className="w-3.5 h-3.5" /> Generate .zip</>
              )}
            </button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
